# Import the csv first

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Yoga Leads.csv to Yoga Leads.csv

In [2]:
import pandas as pd

df = pd.read_csv("Yoga Leads.csv")
df.head()

,Institute Name,Industry,Rating,Reviews,Contact,rllt__details 4,rllt__details 5,Reviews.1,Website,Location
0,Yog with Sushmita,· Yoga studio,4.8,(156),· +91 70453 52810,· Closes 9:30 PM,Open,"""Love the positive energy here & the instructo...",https://www.sushmitamukhia.co.in/,"https://www.google.com/maps/dir//Plot+no+18a,+..."
1,"Yoga Vidya Niketan""s ""YOG BHAVAN""",· Yoga studio,4.8,(263),· +91 93216 43305,· Closes 8 PM,Open,"""The course prepares one as a confident teach...",https://yogavidyaniketan.zohocommerce.in/,https://www.google.com/maps/dir//Yoga+Vidya+Ni...
2,International Sahaja Yoga Research and Health ...,· Yoga studio,4.8,(256),· +91 83691 10612,· Closes 6 PM,Open,"""Adopt Sahaja meditation , elevate your life.""",https://www.sahajahealthcentre.com/,https://www.google.com/maps/dir//International...
3,Yoga Sadhana Mandir,· Yoga studio,4.9,(160),· +91 98673 85786,· Closes 9 PM,Open,"""In this classes, the teachers are really wel...",https://www.ysmyoga.com/,https://www.google.com/maps/dir//Yoga+Sadhana+...
4,Nirvana Yoga Community Studio by Shradha,· Yoga studio,4.9,(128),· +91 98334 14151,· Closes 8 PM,Open,"""I left each session feeling rejuvenated and m...",https://www.youtube.com/watch?v=IOv-F95L3MI,https://www.google.com/maps/dir//Shop+No:+42%2...

# Cleaning raw dataset

In [7]:
df["Contact"] = df["Contact"].str.replace("·", "", regex=False).str.strip()
df["Industry"] = df["Industry"].str.replace("·", "", regex=False).str.strip()

In [12]:
import numpy as np

df["Contact"] = df["Contact"].replace(["", " ", "nan"], np.nan)
df["Website"] = df["Website"].replace(["", " ", "nan"], np.nan)

df = df[df["Contact"].notna() | df["Website"].notna()]

In [13]:
df

,Institute Name,Industry,Rating,Reviews,Contact,rllt__details 4,rllt__details 5,Reviews.1,Website,Location
0,Yog with Sushmita,Yoga studio,4.8,(156),+91 70453 52810,· Closes 9:30 PM,Open,"""Love the positive energy here & the instructo...",https://www.sushmitamukhia.co.in/,"https://www.google.com/maps/dir//Plot+no+18a,+..."
1,"Yoga Vidya Niketan""s ""YOG BHAVAN""",Yoga studio,4.8,(263),+91 93216 43305,· Closes 8 PM,Open,"""The course prepares one as a confident teach...",https://yogavidyaniketan.zohocommerce.in/,https://www.google.com/maps/dir//Yoga+Vidya+Ni...
2,International Sahaja Yoga Research and Health ...,Yoga studio,4.8,(256),+91 83691 10612,· Closes 6 PM,Open,"""Adopt Sahaja meditation , elevate your life.""",https://www.sahajahealthcentre.com/,https://www.google.com/maps/dir//International...
3,Yoga Sadhana Mandir,Yoga studio,4.9,(160),+91 98673 85786,· Closes 9 PM,Open,"""In this classes, the teachers are really wel...",https://www.ysmyoga.com/,https://www.google.com/maps/dir//Yoga+Sadhana+...
4,Nirvana Yoga Community Studio by Shradha,Yoga studio,4.9,(128),+91 98334 14151,· Closes 8 PM,Open,"""I left each session feeling rejuvenated and m...",https://www.youtube.com/watch?v=IOv-F95L3MI,https://www.google.com/maps/dir//Shop+No:+42%2...
...,...,...,...,...,...,...,...,...,...,...
120,Poorvisa Yoga Studio,Yoga studio,5.0,(25),+91 99671 69309,NaN,Temporarily closed,"""Makes and strength training so much fun.""",https://www.poorvisayoga.in/,https://www.google.com/maps/dir//Poorvisa+Yoga...
121,Tapas Yoga by Karishma,Yoga studio,5.0,(81),+91 97734 37322,NaN,Temporarily closed,"""Very affordable sessions and Great experience.""",NaN,https://www.google.com/maps/dir//Tapas+Yoga+by...
122,Maha yoga wellness centre,Yoga studio,NaN,NaN,+91 99308 05559,NaN,Temporarily closed,NaN,http://mahayogawellness.com/,https://www.google.com/maps/dir//Maha+yoga+wel...
123,SD fitness center,Gym,4.7,(22),+91 98677 58262,NaN,Temporarily closed,NaN,https://www.instagram.com/sharadsuryawanshi642...,https://www.google.com/maps/dir//SD+fitness+ce...
124,DNYAN YOG SADHANA,Yoga studio,NaN,NaN,NaN,NaN,Temporarily closed,NaN,https://faq.whatsapp.com/425247423114725/?help...,https://www.google.com/maps/dir//DNYAN+YOG+SAD...

# Download csv

In [14]:
df.to_csv("Yoga Python.csv", index=False)

from google.colab import files
files.download("Yoga Python.csv")